blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/Franklyn-R-Silva/drawer_rail/discussions
    about: Ask questions and discuss ideas with the community.
